### PR TITLE
jpeg quality to 90%

### PR DESCRIPTION
**Pull request by whatisjasongoldstein**

### CODE REVIEW

**Comment by joshmaker** [comment]
Lets make this a settings variable (`DEFAULT_JPG_QUALITY` perhaps) instead of a hardcoded magic number

**Comment by whatisjasongoldstein** [comment]
Good idea.

**Comment by fdintino** [comment]
I would actually like to make this dynamic based on the dimensions of the image.

**Comment by fdintino** [comment]
To expand on that: a 110x90 thumbnail at 90% quality will occasionally have JPEG artifacts (depending on the complexity of the image), and that extra 5% doesn't compromise much in terms of file size. Whereas a 1300x700 retina image (for instance) can get away with quality as low as 85% without noticeable artifacts.

**Comment by fdintino** [comment]
Do we know what quality setting Alan Taylor uses? Would it make sense to have a different quality setting for photo channel?

**Comment by whatisjasongoldstein** [comment]
And then map dimensions to quality parameters in settings? That's an interesting idea.

**Comment by fdintino** [comment]
I think we could make the default settings (optionally) a callable that gets passed the dimensions.

**Comment by earthboundkid** [comment]
Yeah, we could add a function that looks at the image size and returns a quality number. Maybe it multiples width times height then picks the quality based on X pixels → Y quality.

**Comment by whatisjasongoldstein** [comment]
So I think we need three stops:
- Tiny thumbnails (95% or even 100%)
- Regular sized lead images (90%)
- Giant retina things (85%)

Any thoughts on what the boundaries should be?

**Comment by earthboundkid** [comment]
150 x 150 = 22.5k
1,000 x 1,000 = 1m

Seems like reasonable breaks, no?

**Comment by earthboundkid** [comment]
1,300 x 700 is 910k, so maybe make 900k the tipping point if you want that to be reduced quality.

**Comment by joshmaker** [comment]
According to the Pillow docs the scale goes "from 1 (worst) to 95 (best). The default is 75. Values above 95 should be avoided" so we definitely don't want to go above 95.

The image compression settings in v3 of cropduster where we saw JPG compression artifacts on smaller thumbnails was 80, so we know that is too low for small thumbnails, but think we could get away with 90 for even tiny thumbnails.

**Comment by whatisjasongoldstein** [comment]
Now that I'm somewhat back from the dead, let's revisit.

What about something like that?

```
def get_jpeg_quality(width, height):
    pixels = width * height
    if pixels > 1000 * 800:
        return 85
    elif pixels > 200x200:
        return 90
    return 95
```

Values are somewhat arbitrary. If anyone feels really strongly about what the stops should be, I'm sure any of them are fine.

**Comment by fdintino** [comment]
```python
def get_jpeg_quality(width, height):
    p = math.sqrt(width * height)
    if p >= 1750:
        return 80
    elif p >= 1000:
        return 85
    elif p >= 500:
        return 90
    else:
        return 95

**Comment by whatisjasongoldstein** [comment]
I'm good with that. Will update.

**Comment by joshmaker** [comment]
Can we check a few of our standard 210x130 images and see if we can get away with 90 instead of 95? If we use the quality settings suggested here, almost none of the images on the homepage will get any smaller

**Comment by fdintino** [comment]
The thing about small images is that 95% quality vs 90% quality will make very little difference in the file size. We're really working in the margins there. Whereas for large images we'll make substantial gains.

**Comment by fdintino** [comment]
Also, the new homepage won't have any 210x130 images on it.

**Comment by joshmaker** [comment]
I'm not sure any of the images on the current homepage will actually get any smaller with this change. Even the carousel images won't make the cut: `math.sqrt(650 * 375) => 493.7`

Lets have that last `p >=` kick in a little earlier

**Comment by fdintino** [comment]
sure

**Comment by joshmaker** [comment]
I wrote a quick test for people to look at: http://joshwest/static/pil_test/ resizing thumbnails to 210 px wide at 95, 90, and 85 quality. To my eyes, 90 still looks very good and the images are about 30% smaller. I propose we go with 

```
def get_jpeg_quality(width, height):
    p = math.sqrt(width * height)
    if p >= 1750:
        return 80
    elif p >= 800:
        return 85
    else:
        return 90

**Comment by earthboundkid** [comment]
I agree that 90 looks like the sweet spot of file size to perceptible quality.

**Comment by fdintino** [comment]
If we change `p >= 800` to `p >= 1000`, I'm down.

**Comment by whatisjasongoldstein** [comment]
And that's a consensus :smile: I'll merge this on Monday.

**Pull request closed without merging**
